from pydantic import BaseModel


class ImageData(BaseModel):
    id: str
    represents: str | None
    caption: str | None
    credits: str | None


class CollectionData(BaseModel):
    index: str
    name: str
    entityid: str
    uri: str



class ArtifactData(BaseModel):
    id: str | None
    name: str | None
    type: str | None
    location: str | None
    summary: str | None
    perseus_version: str | None
    entered_by: str | None
    sources_used: str | None
    other_bibliography: str | None
    documentary_references: str | None
    accession_number: str | None
    dimensions: str | None
    region: str | None
    start_date: str | None
    start_mod: str | None
    end_date: str | None
    end_mod: str | None
    unitary_date: str | None
    unitary_mod: str | None
    date_for_sort: str | None
    period: str | None
    period_for_sort: str | None
    culture: str | None
    context: str | None
    context_mod: str | None
    findspot: str | None
    findspot_mod: str | None
    collection: str | None
    date_description: str | None
    collection_history: str | None
    donor: str | None
    condit: str | None
    condition_description: str | None
    comparanda: str | None
    material: str | None
    material_description: str | None
    other_notes: str | None
    architectural_order: str | None
    architect: str | None
    architect_evidence: str | None
    building_type: str | None
    history: str | None
    plan: str | None
    see_also: str | None


class VaseData(BaseModel):
    id: str | None
    name: str | None
    type: str | None
    location: str | None
    summary: str | None
    perseus_version: str | None
    entered_by: str | None
    sources_used: str | None
    other_bibliography: str | None
    documentary_references: str | None
    accession_number: str | None
    dimensions: str | None
    region: str | None
    start_date: str | None
    start_mod: str | None
    end_date: str | None
    end_mod: str | None
    unitary_date: str | None
    unitary_mod: str | None
    date_for_sort: str | None
    period: str | None
    period_for_sort: str | None
    culture: str | None
    context: str | None
    context_mod: str | None
    findspot: str | None
    findspot_mod: str | None
    collection: str | None
    date_description: str | None
    collection_history: str | None
    donor: str | None
    condit: str | None
    condition_description: str | None
    comparanda: str | None
    material: str | None
    material_description: str | None
    other_notes: str | None
    graffiti: str | None
    primary_citation: str | None
    ceramic_phase: str | None
    decoration_description: str | None
    essay_number: str | None
    essay_text: str | None
    inscriptions: str | None
    painter: str | None
    painter_mod: str | None
    attributed_by: str | None
    potter: str | None
    potter_mod: str | None
    beazley_number: str | None
    relief: str | None
    shape: str | None
    shape_description: str | None
    ware: str | None


class CoinData(BaseModel):
    id: str | None
    name: str | None
    type: str | None
    location: str | None
    summary: str | None
    perseus_version: str | None
    entered_by: str | None
    sources_used: str | None
    other_bibliography: str | None
    documentary_references: str | None
    accession_number: str | None
    dimensions: str | None
    region: str | None
    start_date: str | None
    start_mod: str | None
    end_date: str | None
    end_mod: str | None
    unitary_date: str | None
    unitary_mod: str | None
    date_for_sort: str | None
    period: str | None
    period_for_sort: str | None
    culture: str | None
    context: str | None
    context_mod: str | None
    findspot: str | None
    findspot_mod: str | None
    collection: str | None
    date_description: str | None
    collection_history: str | None
    donor: str | None
    condit: str | None
    condition_description: str | None
    comparanda: str | None
    material: str | None
    material_description: str | None
    other_notes: str | None
    actual_weight: str | None
    commentary: str | None
    denomination: str | None
    die_axis: str | None
    issuing_authority: str | None
    obverse_legend: str | None
    obverse_type: str | None
    reverse_legend: str | None
    reverse_type: str | None


class BuildingData(BaseModel):
    id: str | None
    name: str | None
    type: str | None
    location: str | None
    summary: str | None
    perseus_version: str | None
    entered_by: str | None
    sources_used: str | None
    other_bibliography: str | None
    documentary_references: str | None
    accession_number: str | None
    dimensions: str | None
    region: str | None
    start_date: str | None
    start_mod: str | None
    end_date: str | None
    end_mod: str | None
    unitary_date: str | None
    unitary_mod: str | None
    date_for_sort: str | None
    period: str | None
    period_for_sort: str | None
    culture: str | None
    context: str | None
    context_mod: str | None
    findspot: str | None
    findspot_mod: str | None
    collection: str | None
    date_description: str | None
    collection_history: str | None
    donor: str | None
    condit: str | None
    condition_description: str | None
    comparanda: str | None
    material: str | None
    material_description: str | None
    other_notes: str | None
    architectural_order: str | None
    architect: str | None
    architect_evidence: str | None
    building_type: str | None
    history: str | None
    plan: str | None
    see_also: str | None

class SiteData(BaseModel):
    id: str | None
    name: str | None
    type: str | None
    location: str | None
    summary: str | None
    perseus_version: str | None
    entered_by: str | None
    sources_used: str | None
    other_bibliography: str | None
    documentary_references: str | None
    region: str | None
    extent: str | None
    human_name: str | None
    site_type: str | None
    description: str | None
    exploration: str | None
    periods: str | None
    physical: str | None


class GemData(BaseModel):
    id: str | None
    name: str | None
    type: str | None
    location: str | None
    summary: str | None
    perseus_version: str | None
    entered_by: str | None
    sources_used: str | None
    other_bibliography: str | None
    documentary_references: str | None
    accession_number: str | None
    dimensions: str | None
    region: str | None
    start_date: str | None
    start_mod: str | None
    end_date: str | None
    end_mod: str | None
    unitary_date: str | None
    unitary_mod: str | None
    date_for_sort: str | None
    period: str | None
    period_for_sort: str | None
    culture: str | None
    context: str | None
    context_mod: str | None
    findspot: str | None
    findspot_mod: str | None
    collection: str | None
    date_description: str | None
    collection_history: str | None
    donor: str | None
    condit: str | None
    condition_description: str | None
    comparanda: str | None
    material: str | None
    material_description: str | None
    other_notes: str | None
    category: str | None
    object_function: str | None
    graffiti: str | None
    inscription: str | None
    inscription_bibliography: str | None
    original: str | None
    original_or_copy: str | None
    placement: str | None
    primary_citation: str | None
    scale: str | None
    scale_for_sort: str | None
    sculptor: str | None
    sculptor_mod: str | None
    style: str | None
    form_style_description: str | None
    subject_description: str | None
    technique: str | None
    technique_description: str | None
    title: str | None
    sculpture_type: str | None
    in_group: str | None
    in_whole: str | None


class SculptureData(BaseModel):
    id: str | None
    name: str | None
    type: str | None
    location: str | None
    summary: str | None
    perseus_version: str | None
    entered_by: str | None
    sources_used: str | None
    other_bibliography: str | None
    documentary_references: str | None
    accession_number: str | None
    dimensions: str | None
    region: str | None
    start_date: str | None
    start_mod: str | None
    end_date: str | None
    end_mod: str | None
    unitary_date: str | None
    unitary_mod: str | None
    date_for_sort: str | None
    period: str | None
    period_for_sort: str | None
    culture: str | None
    context: str | None
    context_mod: str | None
    findspot: str | None
    findspot_mod: str | None
    collection: str | None
    date_description: str | None
    collection_history: str | None
    donor: str | None
    condit: str | None
    condition_description: str | None
    comparanda: str | None
    material: str | None
    material_description: str | None
    other_notes: str | None
    category: str | None
    object_function: str | None
    graffiti: str | None
    inscription: str | None
    inscription_bibliography: str | None
    original: str | None
    original_or_copy: str | None
    placement: str | None
    primary_citation: str | None
    scale: str | None
    scale_for_sort: str | None
    sculptor: str | None
    sculptor_mod: str | None
    style: str | None
    form_style_description: str | None
    subject_description: str | None
    technique: str | None
    technique_description: str | None
    title: str | None
    sculpture_type: str | None
    in_group: str | None
    in_whole: str | None
    assoc_building: str | None
